/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "atividade.h"


int x=0;
	
cadastro cad[5];

int *
cad_mens_1_svc(cadastro *argp, struct svc_req *rqstp)
{
	static int  result;

	if(argp->op == 1){ //Cadastrar Mensagens
	
	if(x<5){

		if(argp != NULL){
		strcpy(cad[x].user,argp->user);
		strcpy(cad[x].mens,argp->mens);
		
		x++;
			

		printf("Mensagem Cadastrada com sucesso!\n");	
		result = 0; // 0 Representa o sucesso do cadastro da mensagem 	
		}	
	}

		else {
			printf("Há 5 mensagens cadastradas! Nao eh possivel cadastrar mais.\n");
			result = -1; // -1 Representa a falha do cadastro da mensagem

		}
	}


		if(argp->op == 2){ //Ler Mensagens Cadastradas

			int y;

			for(y=0; y<x; y++){
			
				
			printf("Usuario: %s\n", cad[y].user);
			printf("Mensagem: %s\n", cad[y].mens);		
						
			}
		}
			if(argp->op == 3){ //Apagar Mensagens 

							
					
			}

				if(argp->op == 4){ //Apagar Mensagens 
		
				printf("O Cliente encerrou a aplicação!\n");

				result = -4; // -4 Representa o encerramento da conexão pelo cliente
				
					
				}
		



	return &result;
}
