/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "atividade.h"


void
atividade_1(char *host, int op)
{
	int operacao;
	int x;

	operacao = op;

	CLIENT *clnt;
	int  *result_1;
	cadastro  cad_mens_1_arg;
	cadastro cad[5];
	
   if(operacao==1){ 
    
	printf("\nUsuario: ");
  	__fpurge(stdin);
  	fscanf(stdin, " %10[^\n]",cad_mens_1_arg.user);
  	printf("Mensagem: ");
  	__fpurge(stdin);
  	fscanf(stdin, " %50[^\n]", cad_mens_1_arg.mens);

	cad_mens_1_arg.op = 1;
  
      }
      
       
   	if(operacao==2){
     
	cad_mens_1_arg.op = 2;

		for(x=0; x<5; x++)
		{
			printf("Usuario: %s\n", cad[x].user);
			printf("Mensagem: %s\n", cad[x].mens);

		}			

   	}


   		if(operacao==3){

    			printf("\nUsuario: ");
  			__fpurge(stdin);
  			fscanf(stdin, " %10[^\n]",cad_mens_1_arg.user);

			cad_mens_1_arg.op = 3;
     
    		 }



			if(operacao==4){

				cad_mens_1_arg.op = 4;

	  		 }

#ifndef	DEBUG
	clnt = clnt_create (host, ATIVIDADE, ATIVIDADE_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = cad_mens_1(&cad_mens_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Chamada Falhou");
	}


		if(*result_1 == 0){

			printf("Mensagem Cadastrada com sucesso!\n");
		}
			if(*result_1 == -1){

				printf("Mensagem nao cadastrada. Ha 5 mensagens cadastradas!\n");
			}

				if(*result_1 == -2){

					printf("\n");
				}

					if(*result_1 >= 100){
						
							
						printf("Quantidade de mensagens apagadas: %d\n",*result_1-100);
					}
						

							if(*result_1 == -4){

								printf("A conexao foi encerrada!\n");
								exit(0);
							}
		
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int op;
	int x;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];



while(1==1){
    
     
   
    fflush(stdin);
    __fpurge(stdin);
   printf("MENU\n");
   
    fflush(stdin);
    __fpurge(stdin);
   printf("OPCOES:\n\n");
   
    fflush(stdin);
    __fpurge(stdin);
  printf(" 1- Cadastrar mensagem\n");
  
    fflush(stdin);
    __fpurge(stdin); 
  printf("2- Ler Mensagem\n");


    fflush(stdin);
    __fpurge(stdin); 
  printf("3- Apagar Mensagem\n");
  
    fflush(stdin);
    __fpurge(stdin);
   fflush(stdout);
  printf(" 4- Sair da aplicaçao\n >");
   
    fflush(stdin);
    __fpurge(stdin);
   fflush(stdout);
   scanf("%d",&op);

    fflush(stdin);
    __fpurge(stdin);

atividade_1 (host,op);


}

exit (0);
}
