/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "definicao.h"


void
definicao_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	cadastro  func1_1_arg;
	int  *result_2;
	cadastro  func2_1_arg;
	int  *result_3;
	cadastro  func3_1_arg;
	int  *result_4;
	cadastro  func4_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, definicao, definicao_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = func1_1(&func1_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = func2_1(&func2_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = func3_1(&func3_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = func4_1(&func4_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	int op;
	struct cadastro cad;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	definicao_1 (host);

while(op!=4){
    
     
   
    fflush(stdin);
    __fpurge(stdin);
   printf("MENU\n");
   
    fflush(stdin);
    __fpurge(stdin);
   printf("OPCOES:\n\n");
   
    fflush(stdin);
    __fpurge(stdin);
  printf(" 1- Cadastrar mensagem\n");
  
    fflush(stdin);
    __fpurge(stdin); 
  printf("2- Ler Mensagem\n");

 fflush(stdin);
    __fpurge(stdin); 
  printf("3- Apagar Mensagem\n");
  
  
    fflush(stdin);
    __fpurge(stdin);
   fflush(stdout);
  printf(" 4- Sair da aplicaçao\n >");
   
    fflush(stdin);
    __fpurge(stdin);
   fflush(stdout);
   scanf("%d",&op);

    fflush(stdin);
    __fpurge(stdin);
   
   if(op==1)
     { 
       
    fflush(stdin);
    __fpurge(stdin);
       fflush(stdout);
	   printf("\nUsuario: ");
	   
    fflush(stdin);
    __fpurge(stdin);
	   fscanf(stdin, " %10[^\n]",cad.user); 
	 
	 
    fflush(stdin);
    __fpurge(stdin);
	   printf("Mensagem: ");
	  
    fflush(stdin);
    __fpurge(stdin);
	   fscanf(stdin, " %50[^\n]", cad.mens);
	
	
	  
      }
      
   
       
   if(op==2)
   {

	/*
     int j=0;
     buf->op = op;
     if (sendto(s,(void *)buf, sizeof( Op1), 0, (struct sockaddr *)&server, sizeof(server)) < 0){
          perror("sendto()");
          exit(2);
      }
      if(recvfrom(s, (void *)buf, sizeof(Op1), 0, (struct sockaddr *) &server,
            &server_address_size) <0)
      {
       perror("recvfrom()");
       exit(1);
      }
     
      if(buf->op ==0){
	 printf("Nao ha Mensagens!\n\n");
      }
     else{
       
	
      
      
       
      j=buf->op-1;
      printf("Mensagens cadastradas:%d\nUsuario:: %s\nMensagem: %s \n\n", buf->op,buf->usuario,buf->msg);
      while(j != 0){
      if(recvfrom(s, (void *)buf, sizeof(Op1), 0, (struct sockaddr *) &server,
            &server_address_size) <0)
      {
       perror("recvfrom()");
       exit(1);
      }
      
       printf("Mensagens cadastradas:%d\nUsuario:: %s\nMensagem: %s \n\n", buf->op,buf->usuario,buf->msg);
       j--;
      }
     }
     */
   }
   if(op==3)
     {

       /*
       if (sendto(s,(void *) buf, sizeof(Op1), 0, (struct sockaddr *)&server, sizeof(server)) < 0){
          perror("sendto()");
          exit(2);
      }
       
       break;
       exit(0);
	*/
     }

	else{

		printf("\n Operacao invalida!\n");
	
			}
	

   }//Fecha While





exit (0);
}
