/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DEFINICAO_H_RPCGEN
#define _DEFINICAO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct cadastro {
	char user[10];
	char mens[50];
	int flag;
};
typedef struct cadastro cadastro;

#define definicao 0x31234567
#define definicao_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define func1 1
extern  int * func1_1(cadastro *, CLIENT *);
extern  int * func1_1_svc(cadastro *, struct svc_req *);
#define func2 2
extern  int * func2_1(cadastro *, CLIENT *);
extern  int * func2_1_svc(cadastro *, struct svc_req *);
#define func3 3
extern  int * func3_1(cadastro *, CLIENT *);
extern  int * func3_1_svc(cadastro *, struct svc_req *);
#define func4 4
extern  int * func4_1(cadastro *, CLIENT *);
extern  int * func4_1_svc(cadastro *, struct svc_req *);
extern int definicao_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define func1 1
extern  int * func1_1();
extern  int * func1_1_svc();
#define func2 2
extern  int * func2_1();
extern  int * func2_1_svc();
#define func3 3
extern  int * func3_1();
extern  int * func3_1_svc();
#define func4 4
extern  int * func4_1();
extern  int * func4_1_svc();
extern int definicao_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cadastro (XDR *, cadastro*);

#else /* K&R C */
extern bool_t xdr_cadastro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DEFINICAO_H_RPCGEN */
